export const UtilityStandards = {
  TRANSFORMER_PAD_MIN_WIDTH_M: 4.0,
  TRANSFORMER_PAD_MIN_LENGTH_M: 4.0,
  CLEARANCE_AROUND_TRANSFORMER_M: 3.0,
  WATER_TANK_MIN_AREA_SQM_PER_CAPITA: 0.5,
  SEWAGE_TREATMENT_MIN_AREA_SQM_PER_CAPITA: 1.0,
  STREET_LIGHT_SPACING_M: 25.0
};
